name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  publish:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: macos-aarch64
            platform: macos-15
            host: "aarch64-apple-darwin"
          - name: macos-x86_64
            platform: macos-13
            host: "x86_64-apple-darwin"

          - name: ubuntu-aarch64
            platform: ubuntu-24.04-arm
            host: "aarch64-unknown-linux-gnu"
          - name: ubuntu-x86_64
            platform: ubuntu-24.04
            host: "x86_64-unknown-linux-gnu"

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install autoconf automake libusb

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake libtool libusb-1.0-0-dev

      - name: Prepare configure script
        run: ./autogen.sh

      - name: Build dfu-util
        run: make

      - name: Rename binary
        shell: bash
        run: |
          bin_path="src/dfu-util"
          cp "$bin_path" "dfu-util-${{ matrix.host }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dfu-util-${{ matrix.host }}
          path: dfu-util-${{ matrix.host }}

  publish-windows:
    defaults:
      run:
        shell: msys2 {0}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: windows-aarch64
            platform: windows-11-arm
            host: "aarch64-pc-windows-msvc"
          - name: windows-x86_64
            platform: windows-2025
            host: "x86_64-pc-windows-msvc"

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            gcc
            unzip
            p7zip

      - name: Download libusb
        run: |
          mkdir -p /tmp/libusb
          curl -L -o /tmp/libusb.7z https://github.com/libusb/libusb/releases/download/v1.0.29/libusb-1.0.29.7z
          7z x /tmp/libusb.7z -o/tmp/libusb

      - name: Build dfu-util
        run: gcc -I/tmp/include -L/tmp/MinGW64/dll -L/tmp/MinGW64/static -DHAVE_WINDOWS_H -o dfu-util main.c dfu_load.c dfu_util.c dfuse.c dfuse_mem.c dfu.c dfu_file.c quirks.c -lusb-1.0

      - name: Rename binary
        shell: bash
        run: |
          bin_path="src/dfu-util.exe"
          cp "$bin_path" "dfu-util-${{ matrix.host }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dfu-util-${{ matrix.host }}
          path: dfu-util-${{ matrix.host }}
